// tslint:disable
/**
 * SCPExC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * DeprecatedUserGeneralControllerApi - axios parameter creator
 * @export
 */
export const DeprecatedUserGeneralControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getPasswd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v0UserPasswdGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v0/user/passwd`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary acquireTraderInfoEnhanced
         * @param {string} control 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v0UserTControlPost: async (control: string, body?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'control' is not null or undefined
            if (control === null || control === undefined) {
                throw new RequiredError('control','Required parameter control was null or undefined when calling v0UserTControlPost.');
            }
            const localVarPath = `/v0/user/t/{control}`
                .replace(`{${"control"}}`, encodeURIComponent(String(control)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeprecatedUserGeneralControllerApi - functional programming interface
 * @export
 */
export const DeprecatedUserGeneralControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getPasswd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v0UserPasswdGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await DeprecatedUserGeneralControllerApiAxiosParamCreator(configuration).v0UserPasswdGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary acquireTraderInfoEnhanced
         * @param {string} control 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v0UserTControlPost(control: string, body?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await DeprecatedUserGeneralControllerApiAxiosParamCreator(configuration).v0UserTControlPost(control, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DeprecatedUserGeneralControllerApi - factory interface
 * @export
 */
export const DeprecatedUserGeneralControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary getPasswd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v0UserPasswdGet(options?: any): AxiosPromise<string> {
            return DeprecatedUserGeneralControllerApiFp(configuration).v0UserPasswdGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary acquireTraderInfoEnhanced
         * @param {string} control 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v0UserTControlPost(control: string, body?: string, options?: any): AxiosPromise<string> {
            return DeprecatedUserGeneralControllerApiFp(configuration).v0UserTControlPost(control, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeprecatedUserGeneralControllerApi - interface
 * @export
 * @interface DeprecatedUserGeneralControllerApi
 */
export interface DeprecatedUserGeneralControllerApiInterface {
    /**
     * 
     * @summary getPasswd
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeprecatedUserGeneralControllerApiInterface
     */
    v0UserPasswdGet(options?: any): AxiosPromise<string>;

    /**
     * 
     * @summary acquireTraderInfoEnhanced
     * @param {string} control 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeprecatedUserGeneralControllerApiInterface
     */
    v0UserTControlPost(control: string, body?: string, options?: any): AxiosPromise<string>;

}

/**
 * DeprecatedUserGeneralControllerApi - object-oriented interface
 * @export
 * @class DeprecatedUserGeneralControllerApi
 * @extends {BaseAPI}
 */
export class DeprecatedUserGeneralControllerApi extends BaseAPI implements DeprecatedUserGeneralControllerApiInterface {
    /**
     * 
     * @summary getPasswd
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeprecatedUserGeneralControllerApi
     */
    public v0UserPasswdGet(options?: any) {
        return DeprecatedUserGeneralControllerApiFp(this.configuration).v0UserPasswdGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary acquireTraderInfoEnhanced
     * @param {string} control 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeprecatedUserGeneralControllerApi
     */
    public v0UserTControlPost(control: string, body?: string, options?: any) {
        return DeprecatedUserGeneralControllerApiFp(this.configuration).v0UserTControlPost(control, body, options).then((request) => request(this.axios, this.basePath));
    }

}
