// tslint:disable
/**
 * SCPExC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * EmployeeManagementControllerApi - axios parameter creator
 * @export
 */
export const EmployeeManagementControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getEmployees
         * @param {string} page 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersEFindPagePost: async (page: string, body?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling apiUsersEFindPagePost.');
            }
            const localVarPath = `/api/users/e/find/{page}`
                .replace(`{${"page"}}`, encodeURIComponent(String(page)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getEmployee
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersEIdPost: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiUsersEIdPost.');
            }
            const localVarPath = `/api/users/e/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary emplControls
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersEOpPost: async (body?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users/e/op`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeeManagementControllerApi - functional programming interface
 * @export
 */
export const EmployeeManagementControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getEmployees
         * @param {string} page 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsersEFindPagePost(page: string, body?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await EmployeeManagementControllerApiAxiosParamCreator(configuration).apiUsersEFindPagePost(page, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getEmployee
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsersEIdPost(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await EmployeeManagementControllerApiAxiosParamCreator(configuration).apiUsersEIdPost(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary emplControls
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsersEOpPost(body?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await EmployeeManagementControllerApiAxiosParamCreator(configuration).apiUsersEOpPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * EmployeeManagementControllerApi - factory interface
 * @export
 */
export const EmployeeManagementControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary getEmployees
         * @param {string} page 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersEFindPagePost(page: string, body?: string, options?: any): AxiosPromise<string> {
            return EmployeeManagementControllerApiFp(configuration).apiUsersEFindPagePost(page, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getEmployee
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersEIdPost(id: string, options?: any): AxiosPromise<string> {
            return EmployeeManagementControllerApiFp(configuration).apiUsersEIdPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary emplControls
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersEOpPost(body?: string, options?: any): AxiosPromise<string> {
            return EmployeeManagementControllerApiFp(configuration).apiUsersEOpPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EmployeeManagementControllerApi - interface
 * @export
 * @interface EmployeeManagementControllerApi
 */
export interface EmployeeManagementControllerApiInterface {
    /**
     * 
     * @summary getEmployees
     * @param {string} page 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeManagementControllerApiInterface
     */
    apiUsersEFindPagePost(page: string, body?: string, options?: any): AxiosPromise<string>;

    /**
     * 
     * @summary getEmployee
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeManagementControllerApiInterface
     */
    apiUsersEIdPost(id: string, options?: any): AxiosPromise<string>;

    /**
     * 
     * @summary emplControls
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeManagementControllerApiInterface
     */
    apiUsersEOpPost(body?: string, options?: any): AxiosPromise<string>;

}

/**
 * EmployeeManagementControllerApi - object-oriented interface
 * @export
 * @class EmployeeManagementControllerApi
 * @extends {BaseAPI}
 */
export class EmployeeManagementControllerApi extends BaseAPI implements EmployeeManagementControllerApiInterface {
    /**
     * 
     * @summary getEmployees
     * @param {string} page 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeManagementControllerApi
     */
    public apiUsersEFindPagePost(page: string, body?: string, options?: any) {
        return EmployeeManagementControllerApiFp(this.configuration).apiUsersEFindPagePost(page, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary getEmployee
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeManagementControllerApi
     */
    public apiUsersEIdPost(id: string, options?: any) {
        return EmployeeManagementControllerApiFp(this.configuration).apiUsersEIdPost(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary emplControls
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeManagementControllerApi
     */
    public apiUsersEOpPost(body?: string, options?: any) {
        return EmployeeManagementControllerApiFp(this.configuration).apiUsersEOpPost(body, options).then((request) => request(this.axios, this.basePath));
    }

}
