// tslint:disable
/**
 * SCPExC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl  from 'url-polyfill';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * ProductsRelatedControllerApi - axios parameter creator
 * @export
 */
export const ProductsRelatedControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getProductInfo
         * @param {string} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductsInfoProductIdPost: async (productId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            if (productId === null || productId === undefined) {
                throw new RequiredError('productId','Required parameter productId was null or undefined when calling apiProductsInfoProductIdPost.');
            }
            const localVarPath = `/api/products/info/{productId}`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary search
         * @param {string} page 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductsSearchPagePost: async (page: string, body?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling apiProductsSearchPagePost.');
            }
            const localVarPath = `/api/products/search/{page}`
                .replace(`{${"page"}}`, encodeURIComponent(String(page)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProductsRelatedControllerApi - functional programming interface
 * @export
 */
export const ProductsRelatedControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getProductInfo
         * @param {string} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductsInfoProductIdPost(productId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await ProductsRelatedControllerApiAxiosParamCreator(configuration).apiProductsInfoProductIdPost(productId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary search
         * @param {string} page 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProductsSearchPagePost(page: string, body?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await ProductsRelatedControllerApiAxiosParamCreator(configuration).apiProductsSearchPagePost(page, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProductsRelatedControllerApi - factory interface
 * @export
 */
export const ProductsRelatedControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary getProductInfo
         * @param {string} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductsInfoProductIdPost(productId: string, options?: any): AxiosPromise<string> {
            return ProductsRelatedControllerApiFp(configuration).apiProductsInfoProductIdPost(productId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary search
         * @param {string} page 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProductsSearchPagePost(page: string, body?: string, options?: any): AxiosPromise<string> {
            return ProductsRelatedControllerApiFp(configuration).apiProductsSearchPagePost(page, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProductsRelatedControllerApi - interface
 * @export
 * @interface ProductsRelatedControllerApi
 */
export interface ProductsRelatedControllerApiInterface {
    /**
     * 
     * @summary getProductInfo
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsRelatedControllerApiInterface
     */
    apiProductsInfoProductIdPost(productId: string, options?: any): AxiosPromise<string>;

    /**
     * 
     * @summary search
     * @param {string} page 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsRelatedControllerApiInterface
     */
    apiProductsSearchPagePost(page: string, body?: string, options?: any): AxiosPromise<string>;

}

/**
 * ProductsRelatedControllerApi - object-oriented interface
 * @export
 * @class ProductsRelatedControllerApi
 * @extends {BaseAPI}
 */
export class ProductsRelatedControllerApi extends BaseAPI implements ProductsRelatedControllerApiInterface {
    /**
     * 
     * @summary getProductInfo
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsRelatedControllerApi
     */
    public apiProductsInfoProductIdPost(productId: string, options?: any) {
        return ProductsRelatedControllerApiFp(this.configuration).apiProductsInfoProductIdPost(productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary search
     * @param {string} page 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsRelatedControllerApi
     */
    public apiProductsSearchPagePost(page: string, body?: string, options?: any) {
        return ProductsRelatedControllerApiFp(this.configuration).apiProductsSearchPagePost(page, body, options).then((request) => request(this.axios, this.basePath));
    }

}
