// tslint:disable
/**
 * SCPExC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * TraderManagementControllerApi - axios parameter creator
 * @export
 */
export const TraderManagementControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getTraders
         * @param {string} page 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersTFindPagePost: async (page: string, body?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling apiUsersTFindPagePost.');
            }
            const localVarPath = `/api/users/t/find/{page}`
                .replace(`{${"page"}}`, encodeURIComponent(String(page)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getTrader
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersTIdPost: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiUsersTIdPost.');
            }
            const localVarPath = `/api/users/t/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary traderControls
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersTOpPost: async (body?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users/t/op`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TraderManagementControllerApi - functional programming interface
 * @export
 */
export const TraderManagementControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getTraders
         * @param {string} page 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsersTFindPagePost(page: string, body?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await TraderManagementControllerApiAxiosParamCreator(configuration).apiUsersTFindPagePost(page, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getTrader
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsersTIdPost(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await TraderManagementControllerApiAxiosParamCreator(configuration).apiUsersTIdPost(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary traderControls
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsersTOpPost(body?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await TraderManagementControllerApiAxiosParamCreator(configuration).apiUsersTOpPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TraderManagementControllerApi - factory interface
 * @export
 */
export const TraderManagementControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary getTraders
         * @param {string} page 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersTFindPagePost(page: string, body?: string, options?: any): AxiosPromise<string> {
            return TraderManagementControllerApiFp(configuration).apiUsersTFindPagePost(page, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getTrader
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersTIdPost(id: string, options?: any): AxiosPromise<string> {
            return TraderManagementControllerApiFp(configuration).apiUsersTIdPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary traderControls
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersTOpPost(body?: string, options?: any): AxiosPromise<string> {
            return TraderManagementControllerApiFp(configuration).apiUsersTOpPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TraderManagementControllerApi - interface
 * @export
 * @interface TraderManagementControllerApi
 */
export interface TraderManagementControllerApiInterface {
    /**
     * 
     * @summary getTraders
     * @param {string} page 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TraderManagementControllerApiInterface
     */
    apiUsersTFindPagePost(page: string, body?: string, options?: any): AxiosPromise<string>;

    /**
     * 
     * @summary getTrader
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TraderManagementControllerApiInterface
     */
    apiUsersTIdPost(id: string, options?: any): AxiosPromise<string>;

    /**
     * 
     * @summary traderControls
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TraderManagementControllerApiInterface
     */
    apiUsersTOpPost(body?: string, options?: any): AxiosPromise<string>;

}

/**
 * TraderManagementControllerApi - object-oriented interface
 * @export
 * @class TraderManagementControllerApi
 * @extends {BaseAPI}
 */
export class TraderManagementControllerApi extends BaseAPI implements TraderManagementControllerApiInterface {
    /**
     * 
     * @summary getTraders
     * @param {string} page 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TraderManagementControllerApi
     */
    public apiUsersTFindPagePost(page: string, body?: string, options?: any) {
        return TraderManagementControllerApiFp(this.configuration).apiUsersTFindPagePost(page, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary getTrader
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TraderManagementControllerApi
     */
    public apiUsersTIdPost(id: string, options?: any) {
        return TraderManagementControllerApiFp(this.configuration).apiUsersTIdPost(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary traderControls
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TraderManagementControllerApi
     */
    public apiUsersTOpPost(body?: string, options?: any) {
        return TraderManagementControllerApiFp(this.configuration).apiUsersTOpPost(body, options).then((request) => request(this.axios, this.basePath));
    }

}
