export enum UserType{
    DEFAULT, SELLER, CUSTOMER, ADMIN, WAREHOUSE, REGISTRAR
}

export enum GeneralStatus{
    PENDING, APPROVED, REJECTED, ONTHEWAY, CANCELED, FULFILLED, UNKNOWN
}

export const TradeStatus = [
    "PENDING", "APPROVED", "REJECTED", "ONTHEWAY", "CANCELED", "FULFILLED", "UNKNOWN"
]