// tslint:disable
/**
 * SCPExC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PageRequestModel
 */
export interface PageRequestModel {
    /**
     * 
     * @type {string}
     * @memberof PageRequestModel
     */
    SearchField: string;
    /**
     * 
     * @type {string}
     * @memberof PageRequestModel
     */
    SortingField: string;
    /**
     * 
     * @type {string}
     * @memberof PageRequestModel
     */
    SortingMethod: string;
    /**
     * 
     * @type {string}
     * @memberof PageRequestModel
     */
    Keyword: string;
    /**
     * 
     * @type {number}
     * @memberof PageRequestModel
     */
    PageSize: number;
}


