// tslint:disable
/**
 * SCPExC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Trader
 */
export interface Trader {
    /**
     * 
     * @type {number}
     * @memberof Trader
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Trader
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Trader
     */
    contact: string;
    /**
     * 
     * @type {number}
     * @memberof Trader
     */
    type: number;
    /**
     * 
     * @type {number}
     * @memberof Trader
     */
    status: number;
    /**
     * 
     * @type {number}
     * @memberof Trader
     */
    createdDate: number;
    /**
     * 
     * @type {number}
     * @memberof Trader
     */
    birth: number;
    /**
     * 
     * @type {string}
     * @memberof Trader
     */
    passwd: string;
    /**
     * 
     * @type {string}
     * @memberof Trader
     */
    note: string;
    /**
     * 
     * @type {string}
     * @memberof Trader
     */
    locationJson: string;
    /**
     * 
     * @type {string}
     * @memberof Trader
     */
    preferJson: string;
    /**
     * 
     * @type {number}
     * @memberof Trader
     */
    registrar: number;
}


